import { useState, useMemo, useCallback } from "react";

var FONTS=[{id:"jetbrains",n:"JetBrains Mono",f:"'JetBrains Mono',monospace"},{id:"fraunces",n:"Fraunces",f:"'Fraunces',serif"},{id:"monoton",n:"Monoton",f:"'Monoton',sans-serif"},{id:"bungee",n:"Bungee",f:"'Bungee',sans-serif"},{id:"caveat",n:"Caveat",f:"'Caveat',cursive"},{id:"permanent-marker",n:"Permanent Marker",f:"'Permanent Marker',cursive"},{id:"vt323",n:"VT323",f:"'VT323',monospace"},{id:"press-start",n:"Press Start 2P",f:"'Press Start 2P',monospace"},{id:"rubik-glitch",n:"Rubik Glitch",f:"'Rubik Glitch',sans-serif"},{id:"creepster",n:"Creepster",f:"'Creepster',cursive"},{id:"bebas",n:"Bebas Neue",f:"'Bebas Neue',sans-serif"},{id:"archivo-black",n:"Archivo Black",f:"'Archivo Black',sans-serif"},{id:"pirata",n:"Pirata One",f:"'Pirata One',cursive"}];
var GFU="https://fonts.googleapis.com/css2?family=Fraunces:ital,wght@0,300..800;1,300..800&family=JetBrains+Mono:wght@400;600;800&family=VT323&family=Press+Start+2P&family=Rubik+Glitch&family=Monoton&family=Bungee&family=Creepster&family=Pirata+One&family=Caveat:wght@400;700&family=Permanent+Marker&family=Bebas+Neue&family=Archivo+Black&display=swap";
var PAT={leopard:"repeating-conic-gradient(#ff1493 0% 25%,#cc1177 0% 50%) 0 0/30px 30px",stars:"radial-gradient(circle,#fff 1px,transparent 1px) 0 0/40px 40px,#000014",grid:"repeating-linear-gradient(0deg,transparent,transparent 39px,#00ff8833 39px,#00ff8833 40px),repeating-linear-gradient(90deg,transparent,transparent 39px,#00ff8833 39px,#00ff8833 40px),#0a0a0a",checker:"conic-gradient(#000 90deg,#fff 90deg 180deg,#000 180deg 270deg,#fff 270deg) 0 0/40px 40px"};
var TC=["#0a0a0a","#000","#111114","#1a1a2e","#0d1b2a","#1b1b3a","#2d132c","#3a0000","#0a2f1f","#1c1c1c","#f5f1e8","#fff","#ffb6d9","#e8d5b7","#d4e4ed","#c5e8c5","#ffeaa7","#dfe6e9"];
function $m(n){return(n>=0?"+":"−")+"$"+Math.abs(n).toLocaleString()}
function $f(id){var f=FONTS.find(function(x){return x.id===id});return f?f.f:"monospace"}
function genDays(){var d={},t=new Date(),m=0,mo=["🔥","🧊","😤","💀","🎯","😌","⚡","🤑"];for(var i=180;i>=0;i--){var dt=new Date(t);dt.setDate(t.getDate()-i);if(dt.getDay()===0||dt.getDay()===6)continue;m=m*.55+(Math.random()-.42)*900;d[dt.toISOString().slice(0,10)]={pnl:Math.round(m+(Math.random()-.5)*500),trades:Math.max(1,Math.round(3+Math.random()*14)),mood:mo[Math.floor(Math.random()*mo.length)]};}return d}
function buildM(days){var mo={};Object.keys(days).sort().forEach(function(k){var ym=k.slice(0,7);if(!mo[ym])mo[ym]=[];mo[ym].push({date:k,...days[k]});});return mo}

var CM_PK=[{user:"gloss_queen",msg:"love the pink vibes 💕",time:"1h",av:"💅"},{user:"chart_princess",msg:"green week!! 👸",time:"3h",av:"👑"},{user:"boba_trader",msg:"manifesting ✨",time:"1d",av:"🧋"}];
var CM_BL=[{user:"desk_jockey",msg:"solid week. avg R?",time:"2h",av:"📊"},{user:"vol_crusher",msg:"textbook wednesday",time:"5h",av:"🎯"},{user:"tape_worm",msg:"see you at open",time:"1d",av:"📈"}];
var CM_INK=[{user:"sarah_m",msg:"book the 15th? sleeve consult",time:"3h",av:"🎨"},{user:"jake_t",msg:"my piece is incredible 🔥",time:"1d",av:"⭐"},{user:"mia_r",msg:"walk-ins saturdays?",time:"2d",av:"✨"}];
var CM_POD=[{user:"audio_nerd",msg:"can't wait for Dr. Chen!",time:"4h",av:"🎧"},{user:"pod_fan_22",msg:"so natural on mic",time:"1d",av:"🎤"},{user:"media_maven",msg:"would love to guest!",time:"2d",av:"📡"}];
var CM_DK=[{user:"midnight_tape",msg:"quiet ones always eat",time:"2h",av:"🌙"},{user:"after_bell",msg:"journal hits different",time:"6h",av:"📓"},{user:"noir_trader",msg:"clean page clean trades",time:"1d",av:"🖤"}];
var CM_MOM=[{user:"hubby_j",msg:"soccer pickup at 4!",time:"1h",av:"💙"},{user:"bestie_rae",msg:"wine night friday? 🍷",time:"3h",av:"🥂"},{user:"school_admin",msg:"PTA moved to 18th",time:"1d",av:"📋"}];
var CM_CFA=[{user:"quant_mike",msg:"sharpe looking solid",time:"2h",av:"📐"},{user:"macro_sarah",msg:"duration exposure?",time:"5h",av:"🏦"},{user:"alpha_chad",msg:"clean risk-adjusted",time:"1d",av:"📊"}];

function ModalBox(props){return(<div><div onClick={props.onClose} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.85)",zIndex:300}}/><div style={{position:"fixed",top:"50%",left:"50%",transform:"translate(-50%,-50%)",width:"min(520px,94vw)",maxHeight:"85vh",overflowY:"auto",background:"#111",border:"1px solid #333",borderRadius:12,zIndex:301,padding:20,fontFamily:"'JetBrains Mono',monospace",color:"#fff"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><span style={{fontSize:13,fontWeight:700,color:"#00ff88"}}>{"◆ "+props.title}</span><button onClick={props.onClose} style={{background:"#222",border:"none",color:"#fff",width:28,height:28,borderRadius:8,cursor:"pointer",fontSize:14}}>×</button></div>{props.children}</div></div>)}

function CalendarBlock(props){
  var s=props.s,days=props.days,nm=props.nameMode,actMode=props.actMode;
  var ac=s.accent||"#00ff44",lo=s.loss||"#ff2222",fs=s.fontSize||13;
  var names=["Alex M","Jordan","Sam K","","Riley T","","Casey","Morgan","","Jamie","Devon","","Avery",""];
  var acts=["","🧋 boba","","💅 nails","","📚 study","🍵 brunch","","🛍 shop","","🎂 party","✨ chill","","🧘 yoga","","🎬 movie","","📸 pics","","💇 hair",""];
  var[cur,setCur]=useState(function(){var t=new Date();return{y:t.getFullYear(),m:t.getMonth()}});
  var cells=useMemo(function(){var f=new Date(cur.y,cur.m,1),sd=f.getDay(),dim=new Date(cur.y,cur.m+1,0).getDate(),c=[];for(var i=0;i<sd;i++)c.push(null);for(var d=1;d<=dim;d++)c.push(new Date(cur.y,cur.m,d));while(c.length%7)c.push(null);return c},[cur]);
  var mx=useMemo(function(){return Math.max(1,...Object.values(days).map(function(d){return Math.abs(d.pnl)}))},[days]);
  var nb={background:"#ffffff15",border:"none",color:s.color,width:28,height:28,borderRadius:6,cursor:"pointer",fontFamily:"inherit",fontSize:16};
  return(<div style={{width:"100%",height:"100%",display:"flex",flexDirection:"column",fontFamily:$f(s.font)}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10,paddingBottom:8}}>
      <div style={{fontSize:fs*1.5,fontWeight:800,textTransform:"uppercase"}}>{new Date(cur.y,cur.m,1).toLocaleString("en-US",{month:"long",year:"numeric"})}</div>
      <div style={{display:"flex",gap:4}}>
        <button onMouseDown={function(e){e.stopPropagation()}} onClick={function(e){e.stopPropagation();setCur({y:cur.m===0?cur.y-1:cur.y,m:cur.m===0?11:cur.m-1})}} style={nb}>{"‹"}</button>
        <button onMouseDown={function(e){e.stopPropagation()}} onClick={function(e){e.stopPropagation();setCur({y:cur.m===11?cur.y+1:cur.y,m:cur.m===11?0:cur.m+1})}} style={nb}>{"›"}</button>
      </div>
    </div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3,marginBottom:4}}>{["S","M","T","W","T","F","S"].map(function(d,i){return(<div key={i} style={{fontSize:fs*.8,opacity:.45,textAlign:"center",fontWeight:700}}>{d}</div>)})}</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:3,flex:1}}>{cells.map(function(c,i){
      if(!c)return(<div key={i}/>);var k=c.toISOString().slice(0,10),data=days[k];
      if(actMode){var act=acts[i%acts.length];return(<div key={i} style={{background:act?ac+"22":"transparent",border:"1px solid "+(s.color||"#fff")+"15",padding:3,borderRadius:4,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{opacity:.65,fontWeight:700,fontSize:fs*.85}}>{c.getDate()}</div>{act&&(<div style={{fontSize:fs*.7,fontWeight:700,color:ac,lineHeight:1.1}}>{act}</div>)}</div>)}
      if(nm){var n=names[i%names.length];var has=n.length>0;return(<div key={i} style={{background:has?ac+"33":"transparent",border:"1px solid "+(s.color||"#fff")+"15",padding:3,borderRadius:4,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{opacity:.65,fontWeight:700,fontSize:fs*.85}}>{c.getDate()}</div>{has&&(<div style={{fontSize:fs*.75,fontWeight:700,color:ac,lineHeight:1.1}}>{n}</div>)}</div>)}
      var it=data?Math.min(1,Math.abs(data.pnl)/mx):0,base=data?(data.pnl>=0?ac:lo):null,alpha=Math.round(it*220+30).toString(16).padStart(2,"0"),bg=base?base+alpha:"transparent";
      return(<div key={i} style={{background:bg,border:"1px solid "+(s.color||"#fff")+"15",padding:4,borderRadius:4,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{opacity:.65,fontWeight:700,fontSize:fs*.85}}>{c.getDate()}</div>{data&&(<div style={{fontSize:fs*1.2,fontWeight:900,color:data.pnl>=0?ac:lo,lineHeight:1,textShadow:"0 0 6px rgba(0,0,0,.9),0 0 12px "+(data.pnl>=0?ac:lo)+"55"}}>{$m(data.pnl)}</div>)}</div>)
    })}</div></div>)}

function StatsBlock(props){var s=props.s,days=props.days,title=props.title;var ac=s.accent||"#00ff88",lo=s.loss||"#ff3366",fs=s.fontSize||12;var st=useMemo(function(){var v=Object.values(days),tot=v.reduce(function(a,b){return a+b.pnl},0),w=v.filter(function(x){return x.pnl>0}).length,l=v.filter(function(x){return x.pnl<0}).length;return{tot:tot,w:w,l:l,ses:v.length,best:Math.max(...v.map(function(x){return x.pnl})),worst:Math.min(...v.map(function(x){return x.pnl})),wr:v.length?Math.round(w/v.length*100):0}},[days]);var rows=[["NET P&L",$m(st.tot),st.tot>=0?ac:lo],["WIN RATE",st.wr+"%"],["W / L",st.w+" / "+st.l],["BEST",$m(st.best),ac],["WORST",$m(st.worst),lo]];return(<div style={{display:"flex",flexDirection:"column",gap:7,width:"100%",height:"100%"}}><div style={{fontWeight:800,letterSpacing:".1em",paddingBottom:6,borderBottom:"1px solid "+(s.color||"#fff")+"33",textShadow:"0 0 8px "+(s.color||"#fff")+"44"}}>{"◆ "+(title||"STATS")}</div>{rows.map(function(r,i){return(<div key={i} style={{display:"flex",justifyContent:"space-between",fontSize:fs}}><span style={{opacity:.6,fontSize:fs*.85,fontWeight:600}}>{r[0]}</span><span style={{fontWeight:900,color:r[2]||s.color,textShadow:"0 0 6px "+(r[2]||s.color||"#fff")+"44"}}>{r[1]}</span></div>)})}</div>)}

function CommentsSection(props){var s=props.s,title=props.title,cm=props.cm,inp=props.inp,si=props.si,op=props.op;return(<div style={{display:"flex",flexDirection:"column",width:"100%",height:"100%"}}><div style={{fontWeight:700,letterSpacing:".1em",paddingBottom:6,borderBottom:"1px solid "+(s.color||"#fff")+"22",marginBottom:6}}>{"💬 "+(title||"COMMENTS")}</div><div style={{flex:1,overflowY:"auto",display:"flex",flexDirection:"column",gap:6,marginBottom:6}}>{cm.map(function(g,i){return(<div key={i} style={{borderBottom:"1px solid "+(s.color||"#fff")+"15",paddingBottom:5}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontWeight:700}}>{g.av+" "+g.user}</span><span style={{opacity:.3,fontSize:(s.fontSize||11)*.8}}>{g.time}</span></div><div style={{opacity:.8,marginTop:2}}>{g.msg}</div></div>)})}</div><div style={{display:"flex",gap:4}}><input value={inp} onChange={function(e){si(e.target.value)}} onMouseDown={function(e){e.stopPropagation()}} placeholder="comment..." style={{flex:1,background:"rgba(255,255,255,.08)",border:"1px solid rgba(255,255,255,.15)",color:"#fff",padding:"8px 10px",fontFamily:"'JetBrains Mono',monospace",fontSize:11,outline:"none",borderRadius:6}} onKeyDown={function(e){if(e.key==="Enter"){e.stopPropagation();op()}}}/><button onMouseDown={function(e){e.stopPropagation()}} onClick={function(e){e.stopPropagation();op()}} style={{background:s.color||"#fff",color:s.bg||"#000",border:"none",padding:"0 14px",fontFamily:"inherit",fontSize:10,cursor:"pointer",fontWeight:700,borderRadius:6}}>POST</button></div></div>)}

function BlockInner(props){var b=props.b,s=b.style;if(b.type==="text")return(<div style={{width:"100%",height:"100%",display:"flex",alignItems:s.textAlign==="center"?"center":"flex-start",justifyContent:s.textAlign==="center"?"center":"flex-start",whiteSpace:"pre-wrap",overflow:"hidden"}}>{b.content}</div>);if(b.type==="sticker")return(<div style={{width:"100%",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",fontSize:Math.min(b.w,b.h)*.7,lineHeight:1}}>{b.content||"⭐"}</div>);if(b.type==="calendar")return(<CalendarBlock s={s} days={props.days} nameMode={b.nameMode} actMode={b.actMode}/>);if(b.type==="stats")return(<StatsBlock s={s} days={props.days} title={b.title}/>);if(b.type==="comments")return(<CommentsSection s={s} title={b.title} cm={props.cm} inp={props.inp} si={props.si} op={props.op}/>);if(b.type==="soundcloud")return b.content?(<iframe title="sc" width="100%" height="100%" scrolling="no" frameBorder="no" allow="autoplay" src={b.content} style={{border:"none"}}/>):(<div style={{display:"flex",alignItems:"center",justifyContent:"center",width:"100%",height:"100%",opacity:.4,fontSize:11}}>+ SoundCloud URL</div>);if(b.type==="youtube")return b.content?(<iframe title="yt" width="100%" height="100%" src={b.content} frameBorder="0" allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture" allowFullScreen style={{border:"none"}}/>):(<div style={{display:"flex",alignItems:"center",justifyContent:"center",width:"100%",height:"100%",opacity:.4,fontSize:11}}>+ YouTube URL</div>);if(b.type==="image")return b.content?(<img src={b.content} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>):(<div style={{display:"flex",alignItems:"center",justifyContent:"center",width:"100%",height:"100%",opacity:.4,fontSize:11}}>+ Image URL</div>);return null}

function DragBlock(props){
  var b=props.b,sel=props.sel,em=props.em,s=b.style||{};var ref={current:null};
  function dn(e,mode){if(!em)return;e.stopPropagation();props.onSel();ref.current={mx:e.clientX||e.touches?.[0]?.clientX||0,my:e.clientY||e.touches?.[0]?.clientY||0,bx:b.x,by:b.y,bw:b.w,bh:b.h,mode:mode};function mv(ev){var cx=ev.clientX||ev.touches?.[0]?.clientX||0,cy=ev.clientY||ev.touches?.[0]?.clientY||0;var dx=cx-ref.current.mx,dy=cy-ref.current.my;if(ref.current.mode==="move")props.onUp({x:Math.max(0,ref.current.bx+dx),y:Math.max(0,ref.current.by+dy)});else props.onUp({w:Math.max(60,ref.current.bw+dx),h:Math.max(60,ref.current.bh+dy)})}function up(){window.removeEventListener("mousemove",mv);window.removeEventListener("mouseup",up);window.removeEventListener("touchmove",mv);window.removeEventListener("touchend",up)}window.addEventListener("mousemove",mv);window.addEventListener("mouseup",up);window.addEventListener("touchmove",mv,{passive:false});window.addEventListener("touchend",up)}
  var isSt=b.type==="sticker";
  return(<div onClick={function(e){e.stopPropagation();props.onSel()}} onMouseDown={function(e){dn(e,"move")}} onTouchStart={function(e){dn(e,"move")}} style={{position:"absolute",left:b.x,top:b.y,width:b.w,height:b.h,transform:"rotate("+(b.rot||0)+"deg)",background:isSt?"transparent":(s.bg||"transparent"),color:s.color||"#fff",fontFamily:$f(s.font||"jetbrains"),fontSize:s.fontSize||14,border:isSt?"none":(s.border||"none"),borderRadius:s.borderRadius||0,boxShadow:isSt?"none":(s.shadow||"none"),padding:isSt?0:(s.padding||0),textAlign:s.textAlign||"left",cursor:em?"grab":"default",userSelect:"none",overflow:isSt?"visible":"hidden",zIndex:sel?50:10,outline:sel?"2px solid #00ff88":"none",touchAction:"none"}}>
    <BlockInner b={b} days={props.days} cm={props.cm} inp={props.inp} si={props.si} op={props.op}/>
    {em&&sel&&(<div>
      <div onMouseDown={function(e){dn(e,"resize")}} onTouchStart={function(e){dn(e,"resize")}} style={{position:"absolute",right:-6,bottom:-6,width:16,height:16,background:"#00ff88",borderRadius:4,border:"2px solid #000",zIndex:100,cursor:"nwse-resize"}}/>
      {b.type!=="calendar"&&(<button onClick={function(e){e.stopPropagation();props.onDel()}} style={{position:"absolute",top:-10,right:-10,width:24,height:24,background:"#ff3366",color:"#fff",border:"2px solid #000",borderRadius:12,cursor:"pointer",fontSize:12,fontWeight:700,display:"flex",alignItems:"center",justifyContent:"center",zIndex:101}}>×</button>)}
    </div>)}
  </div>)}

function StylePanel(props){
  var b=props.b,s=b.style||{};function us(p){props.onUp({style:p})}
  var cl=["#000","#fff","#ff1493","#00ff88","#ffb000","#00d4ff","#ff3366","#7cffb2","#ffccff","#4a004a","#ffdd00","#ff5500","#ff0000","#1a1a2e","#f5f1e8"];
  var sw={width:32,height:32,borderRadius:8,cursor:"pointer",display:"inline-block"};
  var lbl={fontSize:11,fontWeight:600,opacity:.6,marginBottom:6,display:"block"};
  var isSt=b.type==="sticker";
  return(<aside style={{position:"fixed",top:46,right:0,bottom:0,width:280,background:"#111",borderLeft:"1px solid #333",padding:16,overflowY:"auto",zIndex:180,fontFamily:"'JetBrains Mono',monospace",color:"#fff",fontSize:11}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><span style={{color:"#00ff88",fontSize:12,fontWeight:700}}>{"Edit: "+b.type}</span><button onClick={props.onCl} style={{background:"#222",border:"none",color:"#fff",width:28,height:28,borderRadius:8,cursor:"pointer",fontSize:14}}>×</button></div>
    {isSt&&(<div style={{marginBottom:14}}><label style={lbl}>Emoji / Sticker</label><input style={{width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"12px",fontFamily:"inherit",fontSize:28,outline:"none",borderRadius:8,textAlign:"center"}} value={b.content||""} onChange={function(e){props.onUp({content:e.target.value})}}/></div>)}
    {(b.type==="comments"||b.type==="stats")&&(<div style={{marginBottom:14}}><label style={lbl}>Title</label><input style={{width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"10px",fontFamily:"inherit",fontSize:12,outline:"none",borderRadius:8}} value={b.title||""} onChange={function(e){props.onUp({title:e.target.value})}}/></div>)}
    {b.type==="text"&&(<div style={{marginBottom:14}}><label style={lbl}>Content</label><textarea style={{width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"10px",fontFamily:"inherit",fontSize:12,outline:"none",borderRadius:8,resize:"vertical"}} value={b.content||""} onChange={function(e){props.onUp({content:e.target.value})}} rows={4}/></div>)}
    {(b.type==="soundcloud"||b.type==="youtube")&&(<div style={{marginBottom:14}}><label style={lbl}>{b.type==="youtube"?"YouTube URL":"SoundCloud URL"}</label><input style={{width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"10px",fontFamily:"inherit",fontSize:11,outline:"none",borderRadius:8}} value={b.content||""} onChange={function(e){props.onUp({content:e.target.value})}}/></div>)}
    {b.type==="image"&&(<div style={{marginBottom:14}}><label style={lbl}>Image URL</label><input style={{width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"10px",fontFamily:"inherit",fontSize:11,outline:"none",borderRadius:8}} value={b.content||""} onChange={function(e){props.onUp({content:e.target.value})}}/></div>)}
    <div style={{marginBottom:14}}><label style={lbl}>{"Rotate: "+(b.rot||0)+"°"}</label><input type="range" min={-45} max={45} value={b.rot||0} onChange={function(e){props.onUp({rot:Number(e.target.value)})}} style={{width:"100%",accentColor:"#00ff88"}}/></div>
    {!isSt&&(<div>
      <div style={{marginBottom:14}}><label style={lbl}>Background</label><div style={{display:"flex",gap:4,flexWrap:"wrap",marginBottom:6}}>{cl.map(function(c){return(<div key={c} onClick={function(){us({bg:c})}} style={{...sw,background:c,border:s.bg===c?"3px solid #00ff88":"3px solid #333"}}/>)})}</div></div>
      <div style={{marginBottom:14}}><label style={lbl}>Text Color</label><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{cl.map(function(c){return(<div key={c} onClick={function(){us({color:c})}} style={{...sw,background:c,border:s.color===c?"3px solid #00ff88":"3px solid #333"}}/>)})}</div></div>
      <div style={{marginBottom:14}}><label style={lbl}>Font</label><select style={{width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"10px",fontFamily:"inherit",fontSize:11,outline:"none",borderRadius:8}} value={s.font||"jetbrains"} onChange={function(e){us({font:e.target.value})}}>{FONTS.map(function(f){return(<option key={f.id} value={f.id}>{f.n}</option>)})}</select></div>
      <div style={{marginBottom:14}}><label style={lbl}>{"Size: "+(s.fontSize||14)+"px"}</label><input type="range" min={8} max={120} value={s.fontSize||14} onChange={function(e){us({fontSize:Number(e.target.value)})}} style={{width:"100%",accentColor:"#00ff88"}}/></div>
      <div style={{marginBottom:14}}><label style={lbl}>{"Corners: "+(s.borderRadius||0)}</label><input type="range" min={0} max={50} value={s.borderRadius||0} onChange={function(e){us({borderRadius:Number(e.target.value)})}} style={{width:"100%",accentColor:"#00ff88"}}/></div>
      <div style={{marginBottom:14}}><label style={lbl}>Border</label><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{[["none","none"],["thin","1px solid"],["medium","3px solid"],["thick","6px solid"],["dashed","3px dashed"]].map(function(x){return(<button key={x[0]} onClick={function(){us({border:x[1]==="none"?"none":x[1]+" "+(s.color||"#fff")})}} style={{background:s.border&&s.border.indexOf(x[1].split(" ")[0])===0?"#00ff8833":"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"6px 10px",fontSize:10,cursor:"pointer",fontFamily:"inherit",borderRadius:6}}>{x[0]}</button>)})}</div></div>
      <div style={{marginBottom:14}}><label style={lbl}>Shadow</label><div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{[["none","none"],["drop","4px 4px 0 #000"],["glow-g","0 0 15px #00ff88"],["glow-p","0 0 15px #ff1493"],["soft","0 4px 20px rgba(0,0,0,.4)"]].map(function(x){return(<button key={x[0]} onClick={function(){us({shadow:x[1]})}} style={{background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"6px 10px",fontSize:10,cursor:"pointer",fontFamily:"inherit",borderRadius:6}}>{x[0]}</button>)})}</div></div>
    </div>)}
    {b.type!=="calendar"&&(<button onClick={props.onDel} style={{width:"100%",background:"#ff336622",border:"1px solid #ff3366",color:"#ff3366",padding:10,fontSize:11,cursor:"pointer",marginTop:8,fontFamily:"inherit",borderRadius:8,fontWeight:600}}>🗑 Delete Block</button>)}
    {b.type==="calendar"&&(<div style={{fontSize:10,opacity:.3,marginTop:12,textAlign:"center"}}>Calendar cannot be deleted</div>)}
  </aside>)}

var TPLS=[
  {id:"pink",nm:"PINK MONEY",ds:"Trading · feminine maximalism",cm:CM_PK,pg:{bt:"pattern",bv:"leopard"},bk:[{id:"h",type:"text",x:20,y:15,w:720,h:95,rot:-1,title:"",content:"PINK MONEY 💰",style:{bg:"#000",color:"#ff1493",font:"monoton",fontSize:64,border:"5px solid #ff1493",borderRadius:0,shadow:"8px 8px 0 #00ff88",padding:12,textAlign:"center"}},{id:"c",type:"calendar",x:260,y:125,w:500,h:460,rot:0,title:"",style:{bg:"#0a0a0a",color:"#fff",font:"jetbrains",fontSize:14,border:"5px solid #ffdd00",borderRadius:0,shadow:"8px 8px 0 #000",padding:14,accent:"#00ff44",loss:"#ff2222"}},{id:"b",type:"text",x:20,y:125,w:220,h:110,rot:0,title:"",content:"queen of the tape 👑\nES + NQ\ncoffee first then charts",style:{bg:"#ff1493",color:"#fff",font:"permanent-marker",fontSize:15,border:"4px solid #000",borderRadius:0,shadow:"6px 6px 0 #000",padding:12,textAlign:"left"}},{id:"s",type:"stats",x:20,y:255,w:220,h:200,rot:-1,title:"",style:{bg:"#111",color:"#ff69b4",font:"jetbrains",fontSize:14,border:"3px solid #ff1493",borderRadius:4,shadow:"0 0 15px #ff149366",padding:14,accent:"#00ff44",loss:"#ff2222"}},{id:"e1",type:"sticker",x:680,y:10,w:60,h:60,rot:15,content:"💅",style:{bg:"transparent",color:"#fff",font:"jetbrains",fontSize:40,border:"none",borderRadius:0,shadow:"none",padding:0,textAlign:"center"}},{id:"cm",type:"comments",x:20,y:490,w:500,h:200,rot:0,title:"COMMENTS",style:{bg:"#0a0a0a",color:"#fff",font:"jetbrains",fontSize:11,border:"3px solid #ff1493",borderRadius:12,shadow:"4px 4px 0 #ff1493",padding:16}}]},
  {id:"bloom",nm:"BLOOMBERG",ds:"Trading · amber terminal",cm:CM_BL,pg:{bt:"solid",bv:"#000"},bk:[{id:"h",type:"text",x:20,y:10,w:760,h:55,rot:0,title:"",content:"KOY//TERMINAL · LIVE",style:{bg:"#ffb000",color:"#000",font:"jetbrains",fontSize:26,border:"none",borderRadius:0,shadow:"none",padding:12,textAlign:"left"}},{id:"c",type:"calendar",x:20,y:80,w:480,h:440,rot:0,title:"",style:{bg:"#000",color:"#ffb000",font:"jetbrains",fontSize:14,border:"1px solid #ffb000",borderRadius:0,shadow:"none",padding:16,accent:"#00ff44",loss:"#ff2222"}},{id:"s",type:"stats",x:520,y:80,w:260,h:200,rot:0,title:"ANALYTICS",style:{bg:"#000",color:"#ffb000",font:"jetbrains",fontSize:14,border:"1px solid #ffb000",borderRadius:0,shadow:"none",padding:18}},{id:"n",type:"text",x:520,y:295,w:260,h:170,rot:0,title:"",content:"NOTES:\nPatience on entries.\nCut losers faster.\nSize up after 2 greens.\nRisk 1R max per trade.",style:{bg:"#000",color:"#ffb000",font:"jetbrains",fontSize:13,border:"1px solid #ffb000",borderRadius:0,shadow:"none",padding:18,textAlign:"left"}},{id:"cm",type:"comments",x:20,y:540,w:760,h:200,rot:0,title:"MESSAGES",style:{bg:"#000",color:"#ffb000",font:"jetbrains",fontSize:12,border:"1px solid #ffb000",borderRadius:0,shadow:"none",padding:18}}]},
  {id:"y2k",nm:"IT GIRL AGENDA",ds:"Life · bubblegum itinerary",cm:CM_PK,pg:{bt:"solid",bv:"#ffb6d9"},bk:[{id:"h",type:"text",x:40,y:18,w:700,h:95,rot:-2,title:"",content:"★ it girl agenda ★",style:{bg:"linear-gradient(135deg,#ff1493,#ffccff,#87ceeb)",color:"#fff",font:"rubik-glitch",fontSize:58,border:"6px solid #fff",borderRadius:24,shadow:"0 0 30px #ff1493",padding:14,textAlign:"center"}},{id:"c",type:"calendar",x:310,y:135,w:430,h:390,rot:-1,title:"",actMode:true,style:{bg:"#fff",color:"#4a004a",font:"caveat",fontSize:13,border:"6px solid #ff1493",borderRadius:24,shadow:"8px 8px 0 #ff149366",padding:14,accent:"#ff1493",loss:"#9b59b6"}},{id:"b",type:"text",x:40,y:135,w:250,h:260,rot:2,title:"",content:"♡ april vibes ♡\n\n🧋 boba tuesdays\n💅 nail appt the 12th\n📚 study sesh fri\n🍵 brunch w/ bae sat\n🛍 shopping spree 20th\n🎂 kira's bday party\n✨ manifest & chill",style:{bg:"#ffccff",color:"#4a004a",font:"caveat",fontSize:19,border:"4px dashed #ff1493",borderRadius:24,shadow:"6px 6px 0 #ff1493",padding:16,textAlign:"center"}},{id:"e1",type:"sticker",x:700,y:20,w:55,h:55,rot:20,content:"✨",style:{bg:"transparent",color:"#fff",font:"jetbrains",fontSize:40,border:"none",borderRadius:0,shadow:"none",padding:0,textAlign:"center"}},{id:"cm",type:"comments",x:40,y:550,w:460,h:180,rot:0,title:"DROP A NOTE 💌",style:{bg:"#ffccff",color:"#4a004a",font:"caveat",fontSize:14,border:"4px dashed #ff1493",borderRadius:20,shadow:"6px 6px 0 #ff1493",padding:16}}]},
  {id:"biz",nm:"INK & CO",ds:"Business · tattoo bookings",cm:CM_INK,pg:{bt:"solid",bv:"#f5f1e8"},bk:[{id:"h",type:"text",x:30,y:15,w:740,h:65,rot:0,title:"",content:"INK & CO · TATTOO STUDIO",style:{bg:"#1a1a2e",color:"#f5f1e8",font:"bebas",fontSize:40,border:"none",borderRadius:4,shadow:"0 4px 20px rgba(0,0,0,.15)",padding:12,textAlign:"center"}},{id:"c",type:"calendar",x:30,y:100,w:480,h:420,rot:0,title:"",nameMode:true,style:{bg:"#fff",color:"#1a1a2e",font:"jetbrains",fontSize:12,border:"1px solid #ddd",borderRadius:8,shadow:"0 2px 12px rgba(0,0,0,.08)",padding:16,accent:"#2ecc71",loss:"#e74c3c"}},{id:"b",type:"text",x:530,y:100,w:240,h:200,rot:0,title:"",content:"HOURS\nMon-Fri: 11am-8pm\nSat: 12pm-6pm\nSun: By appointment\n\n📍 247 Atlantic Ave\n📞 (718) 555-0199\n✉ book@inkandco.com",style:{bg:"#fff",color:"#1a1a2e",font:"jetbrains",fontSize:11,border:"1px solid #ddd",borderRadius:8,shadow:"0 2px 12px rgba(0,0,0,.08)",padding:16,textAlign:"left"}},{id:"s2",type:"text",x:530,y:320,w:240,h:90,rot:0,title:"",content:"🟢 = slots open\nNames = booked\nDM or call to reserve",style:{bg:"#1a1a2e",color:"#f5f1e8",font:"jetbrains",fontSize:11,border:"none",borderRadius:8,shadow:"none",padding:14,textAlign:"left"}},{id:"cm",type:"comments",x:530,y:430,w:240,h:240,rot:0,title:"INQUIRIES",style:{bg:"#fff",color:"#1a1a2e",font:"jetbrains",fontSize:10,border:"1px solid #ddd",borderRadius:12,shadow:"0 2px 12px rgba(0,0,0,.08)",padding:14}}]},
  {id:"pod",nm:"ON AIR",ds:"Podcast · guest calendar",cm:CM_POD,pg:{bt:"solid",bv:"#0d1b2a"},bk:[{id:"h",type:"text",x:30,y:15,w:740,h:70,rot:0,title:"",content:"🎙 ON AIR · THE REAL ONES",style:{bg:"#e74c3c",color:"#fff",font:"bebas",fontSize:36,border:"none",borderRadius:6,shadow:"0 4px 20px rgba(231,76,60,.3)",padding:14,textAlign:"center"}},{id:"c",type:"calendar",x:30,y:100,w:440,h:400,rot:0,title:"",nameMode:true,style:{bg:"#0a1628",color:"#e8d5b7",font:"jetbrains",fontSize:12,border:"1px solid #e8d5b733",borderRadius:4,shadow:"none",padding:14,accent:"#e74c3c",loss:"#3498db"}},{id:"b",type:"text",x:490,y:100,w:280,h:200,rot:0,title:"",content:"UPCOMING GUESTS\n\n🎤 Dr. Chen — AI Ethics\n🎤 Maya Ross — VC World\n🎤 Tone Loc — Music Biz\n🎤 Prof. Davis — Econ\n🎤 TBA — You? DM us\n\n🎧 New eps every Thu",style:{bg:"#0a1628",color:"#e8d5b7",font:"jetbrains",fontSize:11,border:"1px solid #e8d5b733",borderRadius:4,shadow:"none",padding:16,textAlign:"left"}},{id:"yt",type:"youtube",x:490,y:320,w:280,h:180,rot:0,title:"",content:"https://www.youtube.com/embed/jfKfPfyJRdk",style:{bg:"#000",color:"#fff",font:"jetbrains",fontSize:10,border:"2px solid #e74c3c",borderRadius:4,shadow:"none",padding:0}},{id:"cm",type:"comments",x:30,y:520,w:740,h:200,rot:0,title:"LISTENER COMMENTS",style:{bg:"#0a1628",color:"#e8d5b7",font:"jetbrains",fontSize:11,border:"1px solid #e8d5b733",borderRadius:8,shadow:"none",padding:16}}]},
  {id:"dark",nm:"AFTER HOURS",ds:"Trading · moody editorial",cm:CM_DK,pg:{bt:"solid",bv:"#0a0a0e"},bk:[{id:"h",type:"text",x:50,y:25,w:700,h:85,rot:0,title:"",content:"after hours.",style:{bg:"transparent",color:"#f5f1e8",font:"fraunces",fontSize:78,border:"none",borderRadius:0,shadow:"none",padding:0,textAlign:"left"}},{id:"c",type:"calendar",x:50,y:130,w:460,h:420,rot:0,title:"",style:{bg:"#111114",color:"#f5f1e8",font:"jetbrains",fontSize:13,border:"1px solid #f5f1e822",borderRadius:2,shadow:"none",padding:18,accent:"#7cffb2",loss:"#ff5c5c"}},{id:"b",type:"text",x:530,y:130,w:240,h:200,rot:0,title:"",content:"the tape runs in my head all night.\n\ncoffee, charts, notebook.",style:{bg:"#111114",color:"#f5f1e8",font:"fraunces",fontSize:15,border:"1px solid #f5f1e822",borderRadius:2,shadow:"none",padding:18,textAlign:"left"}},{id:"s",type:"stats",x:530,y:350,w:240,h:200,rot:0,title:"",style:{bg:"#111114",color:"#f5f1e8",font:"jetbrains",fontSize:12,border:"1px solid #f5f1e822",borderRadius:2,shadow:"none",padding:16}},{id:"cm",type:"comments",x:50,y:570,w:380,h:180,rot:0,title:"WHISPERS",style:{bg:"#111114",color:"#f5f1e8",font:"fraunces",fontSize:13,border:"1px solid #f5f1e822",borderRadius:6,shadow:"none",padding:18}}]},
  {id:"mom",nm:"WORKING MOM",ds:"Life · family schedule",cm:CM_MOM,pg:{bt:"solid",bv:"#fef9f0"},bk:[{id:"h",type:"text",x:30,y:15,w:740,h:70,rot:0,title:"",content:"mama's game plan 🗓",style:{bg:"#c56cf0",color:"#fff",font:"caveat",fontSize:48,border:"none",borderRadius:16,shadow:"0 4px 15px rgba(197,108,240,.3)",padding:12,textAlign:"center"}},{id:"c",type:"calendar",x:30,y:100,w:460,h:420,rot:0,title:"",actMode:true,style:{bg:"#fff",color:"#2d3436",font:"caveat",fontSize:13,border:"2px solid #c56cf0",borderRadius:12,shadow:"0 2px 12px rgba(0,0,0,.06)",padding:16,accent:"#c56cf0",loss:"#fd79a8"}},{id:"b",type:"text",x:510,y:100,w:260,h:280,rot:0,title:"",content:"THIS WEEK:\n\n🏫 School drop-off 7:45am\n💼 Client call 10am Mon\n🏋 Gym MWF 6am\n⚽ Soccer pickup 4pm TuTh\n🛒 Grocery run Wed\n🍷 Wine night Fri 8pm\n👨‍👩‍👧 Family movie Sat\n📖 Sunday meal prep",style:{bg:"#fff",color:"#2d3436",font:"caveat",fontSize:17,border:"2px solid #c56cf0",borderRadius:12,shadow:"0 2px 12px rgba(0,0,0,.06)",padding:18,textAlign:"left"}},{id:"e1",type:"sticker",x:720,y:15,w:50,h:50,rot:12,content:"💪",style:{bg:"transparent",color:"#fff",font:"jetbrains",fontSize:40,border:"none",borderRadius:0,shadow:"none",padding:0,textAlign:"center"}},{id:"cm",type:"comments",x:510,y:400,w:260,h:220,rot:0,title:"FAMILY BOARD",style:{bg:"#fff",color:"#2d3436",font:"caveat",fontSize:13,border:"2px solid #c56cf0",borderRadius:12,shadow:"0 2px 12px rgba(0,0,0,.06)",padding:16}}]},
  {id:"cfa",nm:"FINANCE GUY",ds:"Markets · CFA analytics",cm:CM_CFA,pg:{bt:"solid",bv:"#0a0f1a"},bk:[{id:"h",type:"text",x:20,y:12,w:760,h:55,rot:0,title:"",content:"PORTFOLIO ANALYTICS · Q2 2026",style:{bg:"#0f2744",color:"#6cb4ee",font:"jetbrains",fontSize:24,border:"1px solid #6cb4ee44",borderRadius:2,shadow:"none",padding:14,textAlign:"left"}},{id:"c",type:"calendar",x:20,y:80,w:480,h:440,rot:0,title:"",style:{bg:"#0a0f1a",color:"#8ba4be",font:"jetbrains",fontSize:14,border:"1px solid #6cb4ee33",borderRadius:2,shadow:"none",padding:16,accent:"#2ecc71",loss:"#e74c3c"}},{id:"s",type:"stats",x:520,y:80,w:260,h:210,rot:0,title:"PERFORMANCE",style:{bg:"#0a0f1a",color:"#6cb4ee",font:"jetbrains",fontSize:13,border:"1px solid #6cb4ee33",borderRadius:2,shadow:"none",padding:18,accent:"#2ecc71",loss:"#e74c3c"}},{id:"n",type:"text",x:520,y:305,w:260,h:215,rot:0,title:"",content:"RISK METRICS:\n\nSharpe: 1.84\nSortino: 2.31\nMax DD: -8.2%\nBeta: 0.67\nAlpha: +3.1% ann.\nVol: 12.4%\n\nBench: S&P 500",style:{bg:"#0a0f1a",color:"#8ba4be",font:"jetbrains",fontSize:12,border:"1px solid #6cb4ee33",borderRadius:2,shadow:"none",padding:18,textAlign:"left"}},{id:"cm",type:"comments",x:20,y:540,w:760,h:200,rot:0,title:"ANALYST NOTES",style:{bg:"#0a0f1a",color:"#8ba4be",font:"jetbrains",fontSize:12,border:"1px solid #6cb4ee33",borderRadius:2,shadow:"none",padding:18}}]},
  {id:"notes",nm:"NOTES",ds:"Just a notebook",cm:[],pg:{bt:"solid",bv:"#1c1c1c"},bk:[{id:"h",type:"text",x:30,y:20,w:740,h:50,rot:0,title:"",content:"MY NOTES",style:{bg:"transparent",color:"#fff",font:"bebas",fontSize:36,border:"none",borderRadius:0,shadow:"none",padding:8,textAlign:"left"}},{id:"n",type:"text",x:30,y:85,w:740,h:500,rot:0,title:"",content:"Start writing here...\n\n\n\n\n\n\n\n\n",style:{bg:"#111",color:"#ccc",font:"jetbrains",fontSize:14,border:"1px solid #333",borderRadius:8,shadow:"none",padding:20,textAlign:"left"}}]}
];

function App(){
  var[days]=useState(genDays);var[started,setStarted]=useState(false);var[editMode,setEditMode]=useState(true);var[selectedId,setSelectedId]=useState(null);var[comments,setComments]=useState([]);var[cmInput,setCmInput]=useState("");var[page,setPage]=useState({bt:"solid",bv:"#0a0a0a",bc:""});var[blocks,setBlocks]=useState([]);var[showAdd,setShowAdd]=useState(false);var[showBg,setShowBg]=useState(false);var[showMonths,setShowMonths]=useState(false);var[selMonth,setSelMonth]=useState(null);var[saved,setSaved]=useState([]);var[showSaved,setShowSaved]=useState(false);var[saveName,setSaveName]=useState("");var[copied,setCopied]=useState(false);var[startBg,setStartBg]=useState("#000");var[startImg,setStartImg]=useState("");var[showTheme,setShowTheme]=useState(false);var[history,setHistory]=useState([]);var[histIdx,setHistIdx]=useState(-1);
  var months=useMemo(function(){return buildM(days)},[days]);var mKeys=Object.keys(months).sort().reverse();var selBlock=blocks.find(function(b){return b.id===selectedId});

  function pushHist(bks){var h=history.slice(0,histIdx+1);h.push(JSON.stringify(bks));if(h.length>20)h.shift();setHistory(h);setHistIdx(h.length-1)}
  function undo(){if(histIdx>0){var ni=histIdx-1;setHistIdx(ni);setBlocks(JSON.parse(history[ni]));setSelectedId(null)}}
  function redo(){if(histIdx<history.length-1){var ni=histIdx+1;setHistIdx(ni);setBlocks(JSON.parse(history[ni]));setSelectedId(null)}}

  function ub(id,p){setBlocks(function(prev){var next=prev.map(function(b){if(b.id!==id)return b;return{...b,...p,style:{...b.style,...(p.style||{})}}});pushHist(next);return next})}
  function del(id){var b=blocks.find(function(x){return x.id===id});if(b&&b.type==="calendar")return;setBlocks(function(prev){var next=prev.filter(function(x){return x.id!==id});pushHist(next);return next});setSelectedId(null)}
  function addB(type){var id="b"+Date.now();var defs={text:{w:260,h:100,content:"new text",title:"",style:{bg:"#fff",color:"#000",font:"jetbrains",fontSize:18,border:"2px solid #000",borderRadius:8,shadow:"none",padding:14,textAlign:"left"}},sticker:{w:60,h:60,content:"⭐",rot:0,style:{bg:"transparent",color:"#fff",font:"jetbrains",fontSize:40,border:"none",borderRadius:0,shadow:"none",padding:0,textAlign:"center"}},calendar:{w:500,h:450,title:"",style:{bg:"#0a0a0a",color:"#fff",font:"jetbrains",fontSize:13,border:"3px solid #ffdd00",borderRadius:0,shadow:"6px 6px 0 #000",padding:16,accent:"#00ff44",loss:"#ff2222"}},stats:{w:260,h:200,title:"",style:{bg:"#000",color:"#00ff88",font:"jetbrains",fontSize:12,border:"2px solid #00ff88",borderRadius:4,shadow:"none",padding:14}},comments:{w:500,h:260,title:"COMMENTS",style:{bg:"#0a0a0a",color:"#fff",font:"jetbrains",fontSize:11,border:"2px solid #00ff88",borderRadius:8,shadow:"none",padding:16}},soundcloud:{w:400,h:166,content:"",title:"",style:{bg:"#111",color:"#ff5500",font:"jetbrains",fontSize:10,border:"2px solid #ff5500",borderRadius:8,shadow:"none",padding:0}},youtube:{w:320,h:200,content:"",title:"",style:{bg:"#000",color:"#fff",font:"jetbrains",fontSize:10,border:"2px solid #ff0000",borderRadius:8,shadow:"none",padding:0}},image:{w:200,h:200,content:"",title:"",style:{bg:"#222",color:"#fff",font:"jetbrains",fontSize:10,border:"2px solid #fff",borderRadius:8,shadow:"none",padding:0}}};setBlocks(function(prev){var next=[...prev,{id:id,type:type,x:60+Math.random()*200,y:60+Math.random()*200,rot:0,...(defs[type]||defs.text)}];pushHist(next);return next});setSelectedId(id);setShowAdd(false)}
  function postCm(){if(!cmInput.trim())return;setComments(function(prev){return[{user:"you",msg:cmInput,time:"now",av:"⭐"},...prev]});setCmInput("")}
  function saveL(n){setSaved(function(prev){return[{name:n||"Layout "+(prev.length+1),pg:{...page},bks:JSON.parse(JSON.stringify(blocks)),at:new Date().toLocaleString()},...prev]});setSaveName("")}
  function loadL(l){setPage({...l.pg});setBlocks(JSON.parse(JSON.stringify(l.bks)));setSelectedId(null);setShowSaved(false)}
  function copyShare(){var url=window.location.href;navigator.clipboard.writeText(url).then(function(){setCopied(true);setTimeout(function(){setCopied(false)},2000)})}
  function goBlank(){setBlocks([]);setComments([]);setPage({bt:"solid",bv:"#0a0a0a",bc:""});setSelectedId(null);setHistory([]);setHistIdx(-1);setStarted(true)}

  var bgS=useMemo(function(){if(page.bt==="solid")return{background:page.bv};if(page.bt==="pattern"&&PAT[page.bv])return{background:PAT[page.bv]};if(page.bt==="custom"&&page.bc)return{backgroundImage:"url("+page.bc+")",backgroundRepeat:"repeat",backgroundSize:"auto"};return{background:"#0a0a0a"}},[page]);
  var cH=useMemo(function(){return Math.max(800,...blocks.map(function(b){return b.y+b.h+100}))},[blocks]);
  var btn={background:"#222",color:"#fff",border:"none",padding:"7px 12px",fontFamily:"'JetBrains Mono',monospace",fontSize:11,cursor:"pointer",whiteSpace:"nowrap",borderRadius:6,fontWeight:600};
  var btnA={...btn,background:"#00ff88",color:"#000"};
  var sBg=startImg?{backgroundImage:"url("+startImg+")",backgroundSize:"cover",backgroundPosition:"center"}:{background:startBg};

  if(!started)return(
    <div style={{minHeight:"100vh",minHeight:"100dvh",...sBg,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'JetBrains Mono',monospace",color:"#fff",padding:16,overflowX:"hidden"}}>
      <link href={GFU} rel="stylesheet"/>
      <div style={{maxWidth:580,width:"100%",textAlign:"center"}}>
        <div style={{fontFamily:"'Bungee',sans-serif",fontSize:"clamp(28px,8vw,38px)",letterSpacing:".04em",marginBottom:6,color:"#00ff88",textShadow:"0 2px 20px rgba(0,255,136,.3)"}}>KOY CALENDAR</div>
        <div style={{fontSize:11,opacity:.6,letterSpacing:".2em",marginBottom:28}}>YOUR PAGE · YOUR RULES</div>
        <button onClick={function(){setShowTheme(!showTheme)}} style={{...btn,marginBottom:12,display:"block",width:"100%",border:"1px solid #00ff88",color:"#00ff88",background:"transparent"}}>🎨 Change Theme</button>
        {showTheme&&(<div style={{background:"#000000cc",border:"1px solid #333",borderRadius:12,padding:16,marginBottom:16,textAlign:"left"}}><div style={{fontSize:10,opacity:.5,marginBottom:8}}>Solid Colors</div><div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:12}}>{TC.map(function(c){return(<div key={c} onClick={function(){setStartBg(c);setStartImg("")}} style={{width:32,height:32,background:c,border:startBg===c&&!startImg?"3px solid #00ff88":"3px solid #333",borderRadius:8,cursor:"pointer"}}/>)})}</div><div style={{fontSize:10,opacity:.5,marginBottom:8}}>Or paste image URL</div><input value={startImg} onChange={function(e){setStartImg(e.target.value)}} placeholder="https://..." style={{width:"100%",background:"#111",border:"1px solid #333",color:"#fff",padding:"8px 10px",fontFamily:"inherit",fontSize:11,outline:"none",borderRadius:8}}/></div>)}
        <button onClick={goBlank} style={{...btnA,padding:"14px 28px",fontSize:14,marginBottom:20,display:"block",width:"100%",borderRadius:10}}>Start from Blank Page</button>
        <div style={{fontSize:10,opacity:.4,letterSpacing:".15em",marginBottom:12}}>OR PICK A TEMPLATE</div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{TPLS.map(function(t){return(<button key={t.id} onClick={function(){setPage({...t.pg,bc:""});setBlocks(JSON.parse(JSON.stringify(t.bk)));setComments(t.cm||[]);pushHist(t.bk);setStarted(true)}} style={{background:"#111111dd",border:"1px solid #333",color:"#fff",padding:14,textAlign:"left",cursor:"pointer",fontFamily:"inherit",borderRadius:10}}><div style={{fontSize:13,fontWeight:700,marginBottom:3}}>{t.nm}</div><div style={{fontSize:9,opacity:.5}}>{t.ds}</div></button>)})}</div>
      </div>
    </div>);

  return(
    <div style={{minHeight:"100vh",minHeight:"100dvh",background:"#000",fontFamily:"'JetBrains Mono',monospace",color:"#fff",overflowX:"hidden"}}>
      <link href={GFU} rel="stylesheet"/>
      <div style={{position:"fixed",top:0,left:0,right:0,height:46,background:"#000",borderBottom:"1px solid #222",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 8px",zIndex:200}}>
        <div style={{display:"flex",alignItems:"center",gap:6}}>
          <button onClick={function(){setStarted(false);setSelectedId(null)}} style={{...btn,fontSize:14,padding:"4px 10px"}}>←</button>
          <div style={{width:7,height:7,borderRadius:"50%",background:"#00ff88"}}/>
          <span style={{fontFamily:"'Bungee',sans-serif",fontSize:13}}>KOY</span>
        </div>
        <div style={{display:"flex",gap:4,flexWrap:"wrap",alignItems:"center"}}>
          <button style={btn} onClick={undo} title="Undo">↩</button>
          <button style={btn} onClick={redo} title="Redo">↪</button>
          <button style={btn} onClick={copyShare}>{copied?"✓":"🔗"}</button>
          <button style={btn} onClick={function(){setShowMonths(true);setSelMonth(null)}}>📅</button>
          <button style={btn} onClick={function(){setShowSaved(true)}}>💾</button>
          <button style={btn} onClick={function(){setShowBg(true)}}>bg</button>
          <button style={{...btn,background:"#00ff88",color:"#000"}} onClick={function(){setShowAdd(true)}}>+</button>
          <button style={editMode?btnA:btn} onClick={function(){setEditMode(!editMode);setSelectedId(null)}}>{editMode?"✎":"👁"}</button>
        </div>
      </div>
      <div style={{paddingTop:46}}>
        <div style={{position:"relative",...bgS,minHeight:cH,touchAction:"pan-y"}} onClick={function(e){if(e.target===e.currentTarget)setSelectedId(null)}}>
          {blocks.length===0&&editMode&&(<div style={{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%)",textAlign:"center",opacity:.4}}><div style={{fontSize:18,marginBottom:10}}>Empty Page</div><div style={{fontSize:12}}>Tap + to add blocks</div></div>)}
          {blocks.map(function(b){return(<DragBlock key={b.id} b={b} sel={selectedId===b.id} em={editMode} days={days} cm={comments} inp={cmInput} si={setCmInput} op={postCm} onSel={function(){setSelectedId(b.id)}} onUp={function(p){ub(b.id,p)}} onDel={function(){del(b.id)}}/>)})}
        </div>
      </div>
      {editMode&&selBlock&&(<StylePanel b={selBlock} onUp={function(p){ub(selBlock.id,p)}} onDel={function(){del(selBlock.id)}} onCl={function(){setSelectedId(null)}}/>)}
      {showAdd&&(<ModalBox title="Add Block" onClose={function(){setShowAdd(false)}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{[["calendar","📅 Calendar","schedule / P&L"],["text","📝 Text","headline, bio, notes"],["sticker","⭐ Sticker","emoji anywhere"],["stats","📊 Stats","auto trade data"],["comments","💬 Comments","message board"],["soundcloud","🎵 Music","SoundCloud embed"],["youtube","🎬 Video","YouTube embed"],["image","🖼 Image","photo or graphic"]].map(function(r){return(<button key={r[0]} onClick={function(){addB(r[0])}} style={{background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:14,textAlign:"left",cursor:"pointer",fontFamily:"inherit",borderRadius:10}}><div style={{fontSize:13,fontWeight:700,marginBottom:2}}>{r[1]}</div><div style={{fontSize:9,opacity:.4}}>{r[2]}</div></button>)})}</div></ModalBox>)}
      {showBg&&(<ModalBox title="Page Background" onClose={function(){setShowBg(false)}}><div style={{display:"flex",gap:6,marginBottom:14}}>{["solid","pattern","custom"].map(function(t){return(<button key={t} style={page.bt===t?btnA:btn} onClick={function(){setPage({...page,bt:t})}}>{t}</button>)})}</div>{page.bt==="solid"&&(<div><div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:8}}>{TC.map(function(c){return(<div key={c} onClick={function(){setPage({...page,bv:c})}} style={{width:32,height:32,background:c,border:page.bv===c?"3px solid #00ff88":"3px solid #333",borderRadius:8,cursor:"pointer"}}/>)})}</div><input type="color" value={page.bv||"#000"} onChange={function(e){setPage({...page,bv:e.target.value})}} style={{width:"100%",height:40,background:"#1a1a1a",border:"1px solid #333",borderRadius:8}}/></div>)}{page.bt==="pattern"&&(<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:6}}>{Object.keys(PAT).map(function(k){return(<button key={k} onClick={function(){setPage({...page,bv:k})}} style={{aspectRatio:"1",background:PAT[k],border:page.bv===k?"3px solid #00ff88":"1px solid #333",cursor:"pointer",borderRadius:8}} title={k}/>)})}</div>)}{page.bt==="custom"&&(<input value={page.bc||""} onChange={function(e){setPage({...page,bc:e.target.value})}} placeholder="image URL" style={{width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"10px",fontFamily:"inherit",fontSize:11,outline:"none",borderRadius:8}}/>)}</ModalBox>)}
      {showMonths&&(<ModalBox title="📅 Months" onClose={function(){setShowMonths(false);setSelMonth(null)}}>{selMonth===null?(<div>{mKeys.map(function(ym){var ds=months[ym],tot=ds.reduce(function(a,b){return a+b.pnl},0),wins=ds.filter(function(x){return x.pnl>0}).length,dt=new Date(ym+"-15");return(<button key={ym} onClick={function(){setSelMonth(ym)}} style={{display:"flex",justifyContent:"space-between",alignItems:"center",width:"100%",background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"14px 16px",marginBottom:6,cursor:"pointer",fontFamily:"inherit",textAlign:"left",borderRadius:10}}><div><div style={{fontSize:14,fontWeight:700}}>{dt.toLocaleString("en-US",{month:"long",year:"numeric"})}</div><div style={{fontSize:9,opacity:.4,marginTop:2}}>{ds.length+" sessions · "+wins+" wins"}</div></div><div style={{fontSize:18,fontWeight:700,color:tot>=0?"#00ff88":"#ff3366"}}>{$m(tot)}</div></button>)})}</div>):(<div><button onClick={function(){setSelMonth(null)}} style={{...btn,marginBottom:14}}>← Back</button><div style={{fontSize:16,fontWeight:700,marginBottom:12}}>{new Date(selMonth+"-15").toLocaleString("en-US",{month:"long",year:"numeric"})}</div>{months[selMonth].map(function(d,i){var dt=new Date(d.date+"T12:00:00"),pc=d.pnl>=0?"#00ff88":"#ff3366";return(<div key={i} style={{display:"flex",gap:12,alignItems:"center",borderBottom:"1px solid #222",padding:"10px 0"}}><div style={{width:36,fontSize:20,fontWeight:700,textAlign:"center"}}>{dt.getDate()}</div><div style={{fontSize:11,opacity:.5,width:32}}>{dt.toLocaleString("en-US",{weekday:"short"})}</div><div style={{fontSize:15,fontWeight:800,color:pc,minWidth:90}}>{$m(d.pnl)}</div><div style={{fontSize:10,opacity:.4}}>{d.trades+"t"}</div><div style={{fontSize:14,marginLeft:"auto"}}>{d.mood}</div></div>)})}</div>)}</ModalBox>)}
      {showSaved&&(<ModalBox title="Saved Pages" onClose={function(){setShowSaved(false)}}><div style={{marginBottom:14,display:"flex",gap:6}}><input value={saveName} onChange={function(e){setSaveName(e.target.value)}} placeholder="name this layout..." style={{flex:1,background:"#1a1a1a",border:"1px solid #333",color:"#fff",padding:"10px",fontFamily:"inherit",fontSize:12,outline:"none",borderRadius:8}} onKeyDown={function(e){if(e.key==="Enter")saveL(saveName)}}/><button style={btnA} onClick={function(){saveL(saveName)}}>Save</button></div>{saved.length===0?(<div style={{fontSize:11,opacity:.3,padding:"20px 0",textAlign:"center"}}>No saved pages yet</div>):saved.map(function(sl,i){return(<div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",background:"#1a1a1a",border:"1px solid #333",padding:"12px 14px",marginBottom:6,borderRadius:10}}><div><div style={{fontSize:12,fontWeight:700}}>{sl.name}</div><div style={{fontSize:9,opacity:.3,marginTop:2}}>{sl.at}</div></div><div style={{display:"flex",gap:5}}><button style={btn} onClick={function(){loadL(sl)}}>Load</button><button style={{...btn,color:"#ff3366"}} onClick={function(){setSaved(function(p){return p.filter(function(_,j){return j!==i})})}}>✕</button></div></div>)})}</ModalBox>)}
    </div>);
}

export default App;
